---
# This is a role for setting up the client.

- name: Set default shell and sudo
  user:
    name: 'kypo'
    shell: '/bin/bash'
    group: 'sudo'
    append: yes

- name: Create alias for server
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.20.5 server'

- name: Install packages
  apt:
    pkg:
     - nmap
     - hydra
     - medusa
    update_cache: yes

- name: Add passwords file to the home directory
  copy:
    src: passlist.txt
    dest: /home/kypo/passlist.txt
    owner: kypo
    mode: 0644

...